### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by boragokbakan** [tasts-robots/vulp#16]
So far, I've tried to make the code base macOS compatible by wrapping all Linux specific code or header inclusions with guards: https://github.com/tasts-robots/vulp/pull/15.

The build succeeds with `tools/bazelisk build //...`.

Tests fail, however, when I do `tools/baselisk test //...`. I've attached the logs, but I'm not sure how to interpret them.
[test_fail.log](https://github.com/tasts-robots/vulp/files/11354766/test_fail.log)

**Comment by stephane-caron** [comment]
Thanks @boragokbakan for keeping this issue updated. If I understand correctly you closed it following https://github.com/tasts-robots/vulp/pull/15#discussion_r1200644848?

Since the PR hasn't been merged yet, a better practice is to keep the issue open and link it from the PR using the "Development" section to the right of the PR page:

![image](https://github.com/tasts-robots/vulp/assets/1189580/6fb0e2e5-ef3d-40b1-b9d8-08f1072e5f74)

Or writing "Closes #issue_number" in a commit to the corresponding branch (even better, since then we log exactly which commit solves the issue).
